blank_issues_enabled: false
contact_links:
  - name: GitHub Discussions
    url: https://github.com/Mahmud0808/Iconify/discussions
    about: Discuss anything related to Iconify, or ask and answer questions here.
  - name: Telegram Channel
    url: https://t.me/IconifyOfficial
    about: Follow telegram channel to get latest news and updates.
  - name: Telegram Group
    url: https://t.me/IconifyDiscussion
    about: We recommend to go to this place if you wish to ask a question and want a quicker reply. 
